### ISSUE TITLE
`If 51% of miners use the no-premine client, there will be no premine for Bitcoin Gold` is WRONG

### ISSUE THREAD

**Issue by leto** [realBitcoinGold/BTCGPU#4]
What you say is only true if there were only full wallets, no SPV/light wallets. Light wallets decide which chain that a user wallet will follow, so if you don't do the *work* to make your own wallet and run your own wallet backend servers, this Github repo and your README is pretty worthless. FYI

**Comment by h4x3rotab** [comment]
It's even not true if only full wallets. There are consensus rules to enforce the premine coinbase output script.

**Comment by aayanl** [comment]
If you didnt see the joke, its a play on the argument thrown around by /r/btc saying segwit2x is bitcoin because >90% of miners are running it
